data/datadeps_demo/df.graphml
data/sequencer_demo/another_test_graph.graphml
data/sequencer_demo/df_sequencer_demo.graphml
examples/schedule.jl
src/scheduling.jl

- Algorithms now handled as a callable struct containing graph information
- Data objects no longer scheduled as tasks
Struct allows algorithm to access information about its vertex, including average runtime and size.
Ideas taken from @m-fila in #19.

Configure algorithm runtime, don't schedule data object nodes as algortihms

---

test/runtests.jl
test/scheduling.jl

- Test algorithm dependencies for single graph scheduling
- Test algorithm timeline (predecessor algorithm finished before an algorithm starts) for single graph scheduling
The timeline and data dependencies are taken from Dagger logs. The logs operates on `thunk_id` but the the values returned  from `Dagger.@spawn` is a `DTask` that has it's own id. Dagger has a `Dagger.Sch.EAGER_ID_MAP` to map `DTask`ids  and `thunk_id` but it's supposed to change later

Test single graph scheduling

---

examples/parsing_graphs.jl
src/parsing.jl
src/scheduling.jl
test/parsing.jl
test/scheduling.jl

- Fixed paths to workflow data in the tests
- `parse_graphml` accepts singular objects instead of vectors
The relatives paths to workflow data were broken when running directly`test/runtests.jl`
Now the tests can be run both directly from `test/runtests.jl` and `Pkg.test`

Fix data paths in tests

---

src/scheduling.jl

- Fixed scheduling of algorithms with missing runtime property. A warning is displayed and the default value 0 is used
Scheduling ATLAS/q449 got broken in [#21](https://github.com/key4hep/key4hep-julia-fwk/pull/21) because some of the algorithm vertices don't specify a runtime property. After inspection, it seems that they were never executed in the test job hence the values were missing.
Adding handling missing runtime information should be more flexible  (default for now, could be changed to average later) than putting a  default value in the graphml

Fix scheduling algorithms without runtime property

---

.github/workflows/test.yml
Project.toml
README.md

- added CI test badge in readme
- update project authors

add CI test badge and update authors

---

Project.toml
README.md
bin/schedule.jl
scripts/schedule.jl
src/parsing.jl
src/scheduling.jl

Created script `bin/schedule.jl` to serve as primary interface with framework to schedule graphs.
- New function `run_events`,  replacing the previous `schedule_graph_with_notify` to obscure most of the setup
- Removed `parse_graphs` function since we're interested in scheduling the same graph many times
- Runner script with options for data flow graph, number of events to schedule, and max number of concurrent graphs

Basic runner script using new `run_events` function

---

bin/schedule.jl
src/cpu_crunching.jl
src/scheduling.jl
test/README.md
test/runtests.jl
test/scheduling.jl

- Added skipping cpu crunching in algortihms
- Added `--fast` flag to runner that runs the algorithms without crunching
- Added configuring tests with arguments. Tests by default skip crunching
In some scenarios (testing, experimenting) it's cumbersome to wait for the algorithms to finish crunching. A mechanism to skip crunching and return from an algorithm (almost) immediately is introduced
Closing #28

allow skipping cpu crunching

---

.vscode/settings.json
src/scheduling.jl

- Fixed hardcoded channel size producing deadlocks when scheduling pipelines with concurrency >32

fix hardcoded channel size resulting in deadlocks

---

Project.toml
bin/schedule.jl
src/logging.jl
src/scheduling.jl
test/scheduling.jl

- Renamed `run_events` to `run_pipeline`
- Add tests for running a pipeline of graphs
Adding tests verifying all the graphs in a pipeline were run and finished

Add tests for pipeline scheduling

---

Project.toml
README.md
test/Aqua.jl
test/README.md
test/demo_workflows.jl
test/runtests.jl
test/scheduling.jl

- Added testing with Aqua.jl
- `test/runtest.jl` will activate test environment when running manually
Added testing with Aqua.jl. These test are rather slow so are only run when `"all"` is in the `ARGS`. Testing in "CI" will be enabled once #33 is done

add testing with Aqua.jl

---

test/Aqua.jl
test/README.md
test/demo_workflows.jl
test/parsing.jl
test/scheduling.jl

- fixed tests to make them run standalone
For convenience a specific test set can be included and run in REPL without including the whole `test/runtests.jl`:
```julia
append!(ARGS, <list of args>)
import TestEnv
TestEnv.activate()
include("test/parsing.jl")
```

make tests run standalone

---

src/scheduling.jl
test/demo_workflows.jl
test/scheduling.jl

- Added Event and Dataflow structs
- Fixed event storage for concurrent execution
The pipeline running function introduced in #29 was reusing the parsed graph (graph topology and description) instead of creating a new instance for each event. It went unnoticed that the `schedule_graph` methods mutates the graph by using it for storing algorithms` futures.
As a fix two new structs are introduces:
- `DataFlowGraph` to held immutable information about graph topology and algorithms, and possibly do some graph topology caching
- `Event` holding mutable event specific storage and access to immutable `DataFlowGraph`
- `schedule_graph` is renamed to `schedule_graph!` to indicate it mutates `Event`

fix event storage for concurrent execution

---

bin/schedule.jl
src/scheduling.jl
test/demo_workflows.jl
test/scheduling.jl

- Added event number printout for mockup algorithms
- Introduced algorithm abstract type
- Separated data flow representation and mockup workflow creation
The DataFlow struct was coupled with mockup algorithms. With the changes the DataFlow doesn't care if the algortihms are real or mockups. Still calibration (service?) is required all kind of algorithms and is supposed to be fixed later

separate data flow representation from mockup creation

---

bin/schedule.jl
src/visualization.jl
test/runtests.jl
test/visualization.jl

- Added `dry-run` option to assemble the workflow but skip scheduling it
- Added `dump-plan` option to output execution plan
Adding options to allowing checking inspecting the correctness of graph to be scheduled before it's executed. The `dump-plan` option can produce either textual dot graph or graphical representation of it. The execution graph shows the algortihm vertices and data dependencies between them (no dataobject vertices)
Example:
- Input: data flow
- :sparkles:  **New** :sparkles: Output: plan
- Output: logs

Add outputing execution plan before running

---

bin/schedule.jl
src/visualization.jl

- Renamed `--dot-trace` option to `--logs-graph`
- Added `--logs-raw` option for saving Dagger logs to a text file. 
Implementation of text logs for LocalEventLog for #34. Should  be also working with MultiEventLog. The readability of raw logs is limited but it's the most complete information becasue or other options do some kind of filtering and processing of these.

Add saving raw logs as text file

---

src/cpu_crunching.jl
src/logging.jl
src/scheduling.jl
test/cpu_crunching.jl
test/demo_workflows.jl
test/runtests.jl
test/scheduling.jl

- Using FrameworkDemo flavored logging functions
- Removed magic numbers from crunching

Fix magic numbers in crunching, use wrappers for logging

---

.github/workflows/test.yml

- Run CI jobs for tests with and without skipping CPU crunching
Uses the mechanism introduced in #32 to have  separate jobs for fast and slow tests.
Waiting for new release (1.11.0?) of [julia-actions/julia-runtest](https://github.com/julia-actions/julia-runtest) allowing for test arguments in jobs

use test args in CI tests workflow

---

bin/schedule.jl

- Using standardized entry-point `@main` function in mockup runner
Julia 1.11 added a standard entrypoint `@main` for applications. The entry-point is supposed to be in the future used also when compiling apps. The previously used conditional was just checking if the file is executed as a script

use standardized entrypoint

---

data/ATLAS/q449/cf.graphml
data/ATLAS/q449/df.graphml

- Excluded first events from timings in q449 workflow
Some of the algorithms such as `CondInputLoader` takes much more time to exeuction for the first event (or few first events). The timings are updated with new values calculated from a 1000 event sample skipping the first 100 events
Some of the algorithms lost their timing as they were run only during the first event, hence with skipping it no information is available
Some of the algorithms were permuted in the files but it's not affecting the execution and is just a relic of data preparation

Exclude first events from timings in q449

---

.github/workflows/test.yml

- Updated version of testing CI
Test arguments are now supported in the [julia-runtest](https://github.com/julia-actions/julia-runtest/releases/tag/v1.11.0)

use julia-runtest from tag

---

src/mockup.jl
src/scheduling.jl

- Fixed type instabilities due to using global variable, abstract type field and unspecified parametric type field
Fixing minor issues with type instabilities:
- non-const global
- struct with abstract type
- struct with unspecified parametric type

fix type instabilities

---

bin/schedule.jl
src/scheduling.jl
test/scheduling.jl

- Move CPU-crunching calibration outside of event pipeline as it was artificially increasing reported execution times
CPU-crunching calibration is a part of the setup to run the mockups with CPU-crunchers. It's quite slow and when put inside pipeline inflate the reported execution duration, so it's better to move it outside

move calibrating cpu crunchers outside of pipeline

---

bin/schedule.jl
src/logging.jl
src/mockup.jl
src/scheduling.jl
src/visualization.jl
test/demo_workflows.jl
test/scheduling.jl
test/visualization.jl

- Refer to obtaining Dagger execution logs as trace and reserve name logging for "log" printouts
Previously we used name logs for both printouts like `@info` as well as dagger execution information (for instance`Dagger.fetch_logs!()`). Here I rename dagger execution information logs to traces  and reserve name logs only for printout logging with `@info` and other macros. 
This also incorporates a fix from @SmalRat to replace all `println` inside scheduler and mockup algorithms with logging macros. This way all the logging can be easily redirected to some sink or the information can be filtered with appropriate log-level

Rename dagger logging to tracing, replace printing with real logging

---

tools/Project.toml
tools/gaudi_alg_exec_dist.jl

- Add plotting duration distribution from chrome trace
- Add arguments to specify minimum, maximum and number of bins in duration histogram
So far it was only possible to plot distributions of algorithm durations from the dataflow graphs or Gaudi timeline csv. This add possibility to plot also from chrome trace so there is a convenient way to visualize the execution trace
also adding arguments for some basic histogram configuration so different plots can use the same user-defined axis

Add plotting durations from chrome trace, more histogram options

---

Project.toml
bin/schedule.jl
src/cpu_crunching.jl

- Add option to globally disable logging in `schedule.jl`. Add option to set  user-provided crunching coefficient in `schedule.jl`
- Log effects of CPU-crunching calibration so they can be saved and reproduced.
ENDRELEASENOTES 
This adds a convenient CLI argument to globally disable logging below certain level in the `schedule.jl`. This is different than setting global logger with minimal loglevel, as still some parts might use the global logger but the rest use their own specific loggers. This setting should disable all the loggers.
Also previously the CPU-crunching had to be calculated each time without a possibility to provide crunching coefficients by hand. While in general crunching should be done dynamically as it takes into account the current load on a processor, …

Add disabling logs, setting crunching coefficients from cli

---

bin/schedule.jl

- Add options to run warm-up events before the proper pipeline. Warm-up events aren't included in the timing. If tracing is enabled the warm-up events and cpu-crunching will be saved together to a separate trace
Adding `warmup-count` option to schedule warm-up events before pipeline. That should allow to move most in not all compilation to the warmup phase.
If tracing is enabled cpu-crunching and trace-events will be saved to a separate trace with `_warmup` appended to the filename stem -> crunch calibration will stop appearing in the main trace

Add warm-up events in launcher

---

test/Aqua.jl

- Removed unneeded aqua check for `persistent_tasks`
Previously aqua test for `persistent_tasks` was broken for `GraphMLReader`. Currently it seems to be correctly resolved while aqua still expects it be broken

fix aqua checks

---

Project.toml
bin/schedule.jl
test/Aqua.jl

- Add `--trials` option to `schedule.jl` to repeat pipeline multiple times. Add `--save-timing` option to save timing information to a csv file
Adding scheduling the main pipeline multiple times, measuring the timing information and putting it in a csv file which can be stored to csv. Also adding more control to the pipeline timing printouts. This should it make easier to make and store performance measurements
For know saving timing doesn't include configuration of remote workers

Add repeating pipeline and saving timing information

---

.gitignore
Project.toml
README.md
bin/schedule.jl
src/FrameworkDemo.jl
src/preferences.jl
src/scheduling.jl
test/preferences.jl
test/runtests.jl

- Added mechanism to select package used for distributed computing - either `Distributed` standard library or its thread-safe fork `DistributedNext`.
Dagger introduced support for [DistributedNext](https://github.com/JuliaParallel/DistributedNext.jl) - a thread-safe fork of Distributed since due to bugs in it, it was impossible to consistently schedule jobs using multiprocess:multithread
In this PR a mechanism using `Preferences` is used to configure which package will be used for distributed computing. As per recommendation the default is `DistributedNext`
Supersedes #61

use DistributedNext

---

benchmark/Project.toml
benchmark/README.md
benchmark/throughput.sh
benchmark/throughput_vis.jl

- Add simple script for measuring throughput and another script to make plots
Adding simple bash script that runs `schedule.jl` with different number of threads and saves the timing information to CSV. The csv can be later plotted with another julia script

Add scripts for measuring and plotting throughput

---

src/cpu_crunching.jl

- Minimalized spread of algorithm execution due to vector resizing and allocations in CPU crunching
Removed push!(primes, n) from crunching. Impact is minimal.

Minimize spread of CPU crunching times

---

.github/workflows/test.yml

- Add running test with Julia nightlies
Some of the proposed features are using Julia 1.12 pre-release #82, yet we needed some fixes to run 1.12 (JuliaParallel/Dagger.jl#598, https://github.com/m-fila/GraphMLReader.jl/pull/2, https://github.com/m-fila/GraphMLReader.jl/pull/1). Adding tests on pre-releases to detect it earlier

add running test ci with pre-releases

---

bin/schedule.jl

- Add manually invoking garbage collector after measuring the pipeline execution to avoid cleaning memory from setup or other trials during the pipeline
Run GC before pipeline so garbage from warm-up or previous trials isn't collected during the pipeline. This reduces the gc time and also distribution of gc time for multiple trials is more uniform

run gc before pipeline

---

src/mockup.jl
src/scheduling.jl
test/scheduling.jl

- Cache dependencies and information about dependent algorithms since they are the same for each event
- Replace `missing` with `nothing` for non-existent crunching coefficients
- Mockup algorithms return their IDs
This is a follow up to #87 to make the logic a bit simpler
Since algorithm dependencies are a property of the graph, they are the same for each event and could be reused. I propose to store them in the graph while assembling the data-flow.
The mockup algorithms are changed to return a vector filled with their IDs which then get put into the store, so for testing each data object can be associated with the algorithm that produced it.
Also bringing back scheduling test after rework not to relay on Dagger
Also changed indicating that there are no …

Cache dependencies and dependant algorithms

---

bin/schedule.jl

- Removed extra main for juliac. Since 1.12.0-rc2 it's redundant as juliac can now directly use the standard `@main`.

remove redundant main for juliac
